---
name: Lint

"on":
  push:
    branches: [main]
  pull_request:

jobs:
  ansible:
    uses: nkg/github-actions/.github/workflows/ansible.yml@v2
    with:
      requirements-file: requirements.yml
      run-syntax-check: false
